""" migration

Revision ID: 04b8bec28293
Revises: 8cbb9b065502
Create Date: 2023-06-11 23:03:23.045467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b8bec28293'
down_revision = '8cbb9b065502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'is_active')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
