"""Initial

Revision ID: 381a3b32a45f
Revises: 8cbb9b065502
Create Date: 2023-06-15 10:03:01.711687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381a3b32a45f'
down_revision = '8cbb9b065502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_id'), 'qr', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_id'), table_name='qr')
    op.drop_table('qr')
    # ### end Alembic commands ###
